.PHONY: all clean fclean re

CC = gcc
CFLAGS = -Wall -Wextra -Werror
NAME = libft.a
SOURCES = ft_atoi.c ft_bzero.c ft_freearray.c ft_isalnum.c ft_isalpha.c \
		  ft_isascii.c ft_isdigit.c ft_islower.c ft_isprint.c ft_isspace.c \
		  ft_isupper.c ft_itoa.c ft_lstadd.c ft_lstaddend.c ft_lstdel.c \
		  ft_lstdelone.c ft_lstiter.c ft_lstmap.c ft_lstnew.c ft_memalloc.c \
		  ft_memccpy.c ft_memchr.c ft_memcmp.c ft_memcpy.c ft_memdel.c \
		  ft_memmove.c ft_memset.c ft_putchar.c ft_putchar_fd.c ft_putendl.c \
		  ft_putendl_fd.c ft_putnbr.c ft_putnbr_fd.c ft_putstr.c ft_putstr_fd.c \
		  ft_strcat.c ft_strchr.c ft_strclr.c ft_strcmp.c ft_strcpy.c \
		  ft_strdel.c ft_strdup.c ft_strequ.c ft_striter.c ft_striteri.c \
		  ft_strjoin.c ft_strlcat.c ft_strlen.c ft_strmap.c ft_strmapi.c \
		  ft_strncat.c ft_strncmp.c ft_strncpy.c ft_strnequ.c ft_strnew.c \
		  ft_strnstr.c ft_strplen.c ft_strrchr.c ft_strsplit.c ft_strstr.c \
		  ft_strsub.c ft_strtrim.c ft_tolower.c ft_toupper.c get_next_line.c \
		  ft_bits.c ft_lltoa.c ft_ulltoa_base.c ft_ldtoa.c ft_pow.c
OBJECTS = $(subst .c,.o,$(SOURCES))

all: $(NAME)

$(NAME): $(OBJECTS)
	@ar rc $(NAME) $(OBJECTS)
	@ranlib $(NAME)

%.o: %.c
	@$(CC) $(CFLAGS) -c $< -o $@

clean:
	@rm -rf $(OBJECTS)

fclean:
	@rm -rf $(OBJECTS)
	@rm -rf $(NAME)

re: fclean all
